// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcprakoqvzmpyynjcckv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcHJha29xdnptcHl5bmpjY2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Mzk0MTUsImV4cCI6MjA2MzExNTQxNX0.pWTPfpYzGEclhH2QxdTIecyUr3Z4rD6kDU2t93fm4jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);